import type { Metadata } from "next";
import { DEFAULT_LOCALE, LOCALES, isLocale, type Locale } from "@/i18n/config";

/* SEO helper for the marketing surface.
 *
 * Single source of truth for:
 *   - the canonical site origin (siteUrl)
 *   - the per-page, per-locale title + description copy (PAGE_SEO)
 *   - the Metadata shape every localized page ships: absolute canonical,
 *     hreflang alternates (en, es, x-default), Open Graph and Twitter card.
 *
 * Pages call pageMetadata("pricing", locale) for the static ones or
 * buildMetadata({...}) when the copy comes from data (learn/[slug],
 * prompts/[id]).
 *
 * Domain decision D6 (10 sep 2026): the canonical origin is
 * https://creative.artostudio.ai. NEXT_PUBLIC_SITE_URL overrides it (set in
 * Vercel prod); anything else (legacy vercel.app host, library.artostudio.ai)
 * is 301'd by next.config.ts.
 */

export const DEFAULT_SITE_URL = "https://creative.artostudio.ai";
export const SITE_NAME = "ARTO Studio AI";

/* Request header src/proxy.ts sets with the resolved locale so the root
 * layout (which sits above [locale]) can render <html lang>. */
export const LOCALE_HEADER = "x-locale";

/* Path of the global Open Graph image generated by
 * src/app/opengraph-image.tsx (next/og, 1200x630). */
export const DEFAULT_OG_IMAGE_PATH = "/opengraph-image";

const OG_LOCALE: Record<Locale, string> = { en: "en_US", es: "es_MX" };

export function siteUrl(): string {
  const raw = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  const base = raw && /^https?:\/\//i.test(raw) ? raw : DEFAULT_SITE_URL;
  return base.replace(/\/+$/, "");
}

/* Narrow an unknown [locale] param to a Locale, falling back to the default.
 * Pages already 404 on bad locales in their body; metadata just needs a
 * safe value. */
export function localeOf(value: unknown): Locale {
  return isLocale(value) ? value : DEFAULT_LOCALE;
}

/* "/pricing/" -> "/pricing", "pricing" -> "/pricing", "" -> "/". Drops any
 * query string so canonicals never carry filters. */
function normalizePath(path: string): string {
  const noQuery = path.split(/[?#]/)[0] ?? "";
  const withSlash = noQuery.startsWith("/") ? noQuery : `/${noQuery}`;
  const trimmed = withSlash.replace(/\/+$/, "");
  return trimmed === "" ? "/" : trimmed;
}

/* "/pricing" + "es" -> "/es/pricing"; "/" + "en" -> "/en". */
export function localizedPath(locale: Locale, path: string): string {
  const p = normalizePath(path);
  return `/${locale}${p === "/" ? "" : p}`;
}

export function absoluteUrl(path: string): string {
  return `${siteUrl()}${normalizePath(path)}`;
}

/* Append the brand suffix unless the title already carries it. Used for
 * data-driven titles (learn/[slug], prompts/[id]). */
export function withBrand(title: string): string {
  const clean = title.trim();
  if (clean.toLowerCase().includes(SITE_NAME.toLowerCase())) return clean;
  return `${clean} · ${SITE_NAME}`;
}

/* Trim a description to a search-snippet friendly length on a word boundary. */
export function clampDescription(text: string, max = 155): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > 80 ? cut.slice(0, lastSpace) : cut).replace(/[\s,.;:]+$/, "")}...`;
}

export interface BuildMetadataInput {
  locale: Locale;
  /* Path WITHOUT the locale prefix, e.g. "/pricing" or "/prompts/br-001". */
  path: string;
  title: string;
  description: string;
  /* Site-relative or absolute image URL. Omit for the global OG image.
   * Pass null to set no image via config so the segment's own file-based
   * opengraph-image.tsx / twitter-image.tsx apply (Next only merges the
   * file-based image when the config does not define `images`). */
  ogImage?: string | null;
  noIndex?: boolean;
}

export function buildMetadata(input: BuildMetadataInput): Metadata {
  const { locale, path, title, description, ogImage, noIndex } = input;
  const site = siteUrl();
  const canonical = `${site}${localizedPath(locale, path)}`;

  const languages: Record<string, string> = {};
  for (const l of LOCALES) languages[l] = `${site}${localizedPath(l, path)}`;
  languages["x-default"] = `${site}${localizedPath(DEFAULT_LOCALE, path)}`;

  const imageUrl =
    ogImage === null
      ? null
      : /^https?:\/\//i.test(ogImage ?? "")
        ? (ogImage as string)
        : absoluteUrl(ogImage ?? DEFAULT_OG_IMAGE_PATH);

  const metadata: Metadata = {
    title,
    description,
    alternates: { canonical, languages },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: OG_LOCALE[locale],
      alternateLocale: LOCALES.filter((l) => l !== locale).map((l) => OG_LOCALE[l]),
      url: canonical,
      title,
      description,
      ...(imageUrl ? { images: [{ url: imageUrl, width: 1200, height: 630, alt: title }] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      ...(imageUrl ? { images: [imageUrl] } : {}),
    },
  };

  if (noIndex) metadata.robots = { index: false, follow: false };
  return metadata;
}

/* ------------------------------------------------------------------ copy */

export type SeoPageKey =
  | "home"
  | "prompts"
  | "pricing"
  | "learn"
  | "skills"
  | "agents"
  | "work"
  | "tools"
  | "privacy"
  | "terms"
  | "login"
  | "account"
  | "collections"
  | "collection"
  | "favorites";

interface SeoCopy {
  title: string;
  description: string;
}

interface SeoPage {
  path: string;
  noIndex?: boolean;
  copy: Record<Locale, SeoCopy>;
}

/* Titles follow "{Page} · ARTO Studio AI" and are unique per page and per
 * locale. Spanish is Mexican Spanish. No em dashes. */
export const PAGE_SEO: Record<SeoPageKey, SeoPage> = {
  home: {
    path: "/",
    copy: {
      en: {
        title: "ARTO Studio AI · The creative studio that never sleeps",
        description:
          "3,000 prompts, AI creative skills and autonomous agents built on ARTO's real methodology: strategy, creativity, narrative and production. 15+ years with Google, Nike and Uber, now self-serve.",
      },
      es: {
        title: "ARTO Studio AI · El estudio creativo que nunca duerme",
        description:
          "3,000 prompts, skills creativas con IA y agentes autónomos con la metodología real de ARTO: estrategia, creatividad, narrativa y producción. 15+ años con Google, Nike y Uber, ahora en autoservicio.",
      },
    },
  },
  prompts: {
    path: "/prompts",
    copy: {
      en: {
        title: "Prompt Library · ARTO Studio AI",
        description:
          "Browse 3,000 curated AI prompts across branding, design, copywriting, photography, video, UX and more. Filter by vertical, tool, difficulty and tier, in English and Spanish.",
      },
      es: {
        title: "Biblioteca de prompts · ARTO Studio AI",
        description:
          "Explora 3,000 prompts de IA curados para branding, diseño, copywriting, fotografía, video, UX y más. Filtra por vertical, herramienta, dificultad y plan, en español e inglés.",
      },
    },
  },
  pricing: {
    path: "/pricing",
    copy: {
      en: {
        title: "Pricing · ARTO Studio AI",
        description:
          "Start free. Unlock the full prompt library for $9 a month. Skills Studio and AI Agents are coming soon.",
      },
      es: {
        title: "Precios · ARTO Studio AI",
        description:
          "Empieza gratis. Desbloquea la biblioteca completa de prompts por $9 al mes. Skills Studio y Agentes de IA llegan pronto.",
      },
    },
  },
  learn: {
    path: "/learn",
    copy: {
      en: {
        title: "Learn: AI prompt guides by vertical · ARTO Studio AI",
        description:
          "Guides on how to use AI prompts in branding, graphic design, copywriting, photography, video, UX and other creative verticals, plus articles from the ARTO journal.",
      },
      es: {
        title: "Aprende: guías de prompts de IA por vertical · ARTO Studio AI",
        description:
          "Guías para usar prompts de IA en branding, diseño gráfico, copywriting, fotografía, video, UX y otras verticales creativas, más artículos del journal de ARTO.",
      },
    },
  },
  skills: {
    path: "/skills",
    copy: {
      en: {
        title: "Skills Studio · ARTO Studio AI",
        description:
          "AI creative skills that run ARTO's methodology end to end: brand positioning, naming, messaging and more. Structured outputs you can put to work the same day.",
      },
      es: {
        title: "Skills Studio, skills creativas con IA · ARTO Studio AI",
        description:
          "Skills creativas con IA que corren la metodología de ARTO de principio a fin: posicionamiento de marca, naming, mensajes y más. Resultados estructurados listos para usar el mismo día.",
      },
    },
  },
  agents: {
    path: "/agents",
    copy: {
      en: {
        title: "AI Agents · ARTO Studio AI",
        description:
          "Autonomous creative agents that plan, produce and iterate on brand work using ARTO's methodology. Join the waitlist.",
      },
      es: {
        title: "Agentes de IA · ARTO Studio AI",
        description:
          "Agentes creativos autónomos que planean, producen e iteran trabajo de marca con la metodología de ARTO. Únete a la lista de espera.",
      },
    },
  },
  work: {
    path: "/work",
    copy: {
      en: {
        title: "Work · ARTO Studio AI",
        description:
          "Selected branding, web and campaign projects by ARTO for clients such as Grupo Proeza and Kolab Ventures. The methodology behind ARTO Studio AI, in practice.",
      },
      es: {
        title: "Trabajo · ARTO Studio AI",
        description:
          "Proyectos seleccionados de branding, web y campañas de ARTO para clientes como Grupo Proeza y Kolab Ventures. La metodología detrás de ARTO Studio AI, en la práctica.",
      },
    },
  },
  tools: {
    path: "/tools",
    copy: {
      en: {
        title: "AI Tools Reference · ARTO Studio AI",
        description:
          "Reference catalog of generative AI tools grouped by output: text, image, video, music and voice. Pick the right tool for each prompt.",
      },
      es: {
        title: "Herramientas de IA · ARTO Studio AI",
        description:
          "Catálogo de referencia de herramientas de IA generativa agrupadas por salida: texto, imagen, video, música y voz. Elige la herramienta correcta para cada prompt.",
      },
    },
  },
  privacy: {
    path: "/privacy",
    copy: {
      en: {
        title: "Privacy Policy · ARTO Studio AI",
        description:
          "How ARTO Studio AI collects, uses and stores personal data, and the rights you have over it.",
      },
      es: {
        title: "Política de privacidad · ARTO Studio AI",
        description:
          "Cómo ARTO Studio AI recopila, usa y guarda datos personales, y los derechos que tienes sobre ellos.",
      },
    },
  },
  terms: {
    path: "/terms",
    copy: {
      en: {
        title: "Terms of Service · ARTO Studio AI",
        description:
          "Terms that govern the use of ARTO Studio AI: accounts, acceptable use, subscriptions and licensing of prompts.",
      },
      es: {
        title: "Términos de servicio · ARTO Studio AI",
        description:
          "Términos que rigen el uso de ARTO Studio AI: cuentas, uso aceptable, suscripciones y licencia de los prompts.",
      },
    },
  },
  login: {
    path: "/login",
    copy: {
      en: {
        title: "Sign in · ARTO Studio AI",
        description:
          "Sign in with a magic link or Google to save favorites, manage collections and unlock the Pro catalog.",
      },
      es: {
        title: "Inicia sesión · ARTO Studio AI",
        description:
          "Inicia sesión con un enlace mágico o con Google para guardar favoritos, administrar colecciones y desbloquear el catálogo Pro.",
      },
    },
  },
  account: {
    path: "/account",
    noIndex: true,
    copy: {
      en: { title: "Account · ARTO Studio AI", description: "Manage your ARTO Studio AI account, plan and billing." },
      es: { title: "Cuenta · ARTO Studio AI", description: "Administra tu cuenta, plan y facturación de ARTO Studio AI." },
    },
  },
  collections: {
    path: "/collections",
    noIndex: true,
    copy: {
      en: { title: "Collections · ARTO Studio AI", description: "Your saved prompt collections." },
      es: { title: "Colecciones · ARTO Studio AI", description: "Tus colecciones de prompts guardadas." },
    },
  },
  collection: {
    path: "/collections",
    noIndex: true,
    copy: {
      en: { title: "Collection · ARTO Studio AI", description: "A saved prompt collection." },
      es: { title: "Colección · ARTO Studio AI", description: "Una colección de prompts guardada." },
    },
  },
  favorites: {
    path: "/favorites",
    noIndex: true,
    copy: {
      en: { title: "Favorites · ARTO Studio AI", description: "Prompts you marked as favorite." },
      es: { title: "Favoritos · ARTO Studio AI", description: "Los prompts que marcaste como favoritos." },
    },
  },
};

/* Metadata for a static marketing page. `pathOverride` lets dynamic
 * children (collections/[id]) keep their own canonical. */
export function pageMetadata(key: SeoPageKey, locale: Locale, pathOverride?: string): Metadata {
  const page = PAGE_SEO[key];
  const copy = page.copy[locale];
  return buildMetadata({
    locale,
    path: pathOverride ?? page.path,
    title: copy.title,
    description: copy.description,
    noIndex: page.noIndex,
  });
}
